[settings]
temperature = 0.69
presence_penalty = 0.45
frequency_penalty = 0.65
reruns = 0
rerun_lines = 7
max_retries = 2
max_tokens = 2048

input = ""
prompt = "prompts/eldenring.txt"
output = "eldenring-1.mp3"

# ------------------------------------------------

[characters]

[characters.narrator]
voice = "Brian"

[characters.Narrator]
voice = "Brian"

[characters.mss]
voice = "Geraint"
ssml = "<speak><prosody amazon:max-duration=\"60s\" pitch=\"+2000%\" rate=\"x-fast\">{TEXT}</prosody></speak>"

[characters."Uncle Cheeseburger"]
voice = "Matthew"

[characters.man1]
voice = "Matthew"

[characters.male1]
voice = "Matthew"
ssml = "<speak><prosody amazon:max-duration=\"60s\" pitch=\"+2000%\" rate=\"x-fast\">{TEXT}</prosody></speak>"

[characters.male2]
voice = "Russell"

[characters.male3]
voice = "Matthew"

[characters.son]
voice = "Justin"

[characters.male4]
voice = "Geraint"
ssml = "<speak><prosody amazon:max-duration=\"60s\" pitch=\"-2000%\" rate=\"slow\">{TEXT}</prosody></speak>"

[characters.wife]
voice = "Joanna"

[characters.female1]
voice = "Joanna"

[characters.feefee]
voice = "Joanna"

[characters.female2]
voice = "Kendra"

[characters.female3]
voice = "Salli"

[characters.female4]
voice = "Kimberly"

[characters.female5]
voice = "Ivy"

[characters.tkt]
voice = "Justin"

[characters.unknown]
voice = "Russell"
