
[settings]
temperature = 0.6
presence_penalty = 0.4
frequency_penalty = 0.7
reruns = 3
rerun_lines = 8
max_retries = 2
max_tokens = 2048

#input = "a Movie Theater Ticket Sales Person"
input = "rob a bank"

[characters]

[characters.narrator]
voice = "Brian"

[characters.mss]
voice = "Geraint"
ssml = "<speak><prosody amazon:max-duration=\"60s\" pitch=\"+2000%\" rate=\"x-fast\">{TEXT}</prosody></speak>"

[characters.male1]
voice = "Justin"

[characters.male2]
voice = "Russell"

[characters.male3]
voice = "Matthew"

[characters.wife]
voice = "Joanna"

[characters.female1]
voice = "Joanna"

[characters.female2]
voice = "Kendra"

[characters.female3]
voice = "Salli"

[characters.female4]
voice = "Kimberly"

[characters.female5]
voice = "Ivy"

[characters.tkt]
voice = "Justin"

[characters.unknown]
voice = "Russell"
