
[settings]
temperature = 0.6
presence_penalty = 0.3
frequency_penalty = 0.1
reruns = 1
rerun_lines = 7

[characters]

[characters.narrator]
voice = "Brian"

[characters.mss]
voice = "Geraint"
ssml = "<speak><prosody amazon:max-duration=\"60s\" pitch=\"+2000%\" rate=\"x-fast\">{TEXT}</prosody></speak>"

[characters.wife]
voice = "Joanna"

[characters.woman]
voice = "Ayanda"

[characters.son]
voice = "Justin"

[characters.unknown]
voice = "Russell"
