
[settings]
temperature = 0.60
presence_penalty = 0.4
frequency_penalty = 0.2

[characters]

[characters.narrator]
voice = "Brian"

[characters.mss]
voice = "Matthew"

[characters.wife]
voice = "Joanna"

[characters.woman]
voice = "Joanna"

[characters.son]
voice = "Justin"

[characters.unknown]
voice = "Joey"
